'use strict';
const width = 10;
const height = 3;
const area = width * height;
console.log('valueof area:', area);
console.log('typeof area:', typeof area);
const bill = 50;
const payment = 100;
const change = payment - bill;
console.log('valueof change:', change);
console.log('typeof change:', typeof change);
const quizzes = 10;
const midterm = 35;
const final = 45;
const grade = (quizzes + midterm + final) / 3;
console.log('valueof grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Karen';
const lastName = 'Bu';
const fullName = firstName + ' ' + lastName;
console.log('valueof fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 5;
const isAcidic = pH < 7;
console.log('valueof isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 300;
const isSparta = headCount == 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
